[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm ci && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://textile-printing-api.onrender.com"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_NAME = "Digital Textile Printing System"
  REACT_APP_VERSION = "1.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"
  environment = { REACT_APP_API_URL = "https://textile-printing-api.onrender.com" }

[context.branch-deploy]
  command = "npm ci && npm run build" 